export type PermissionKey =
  | 'dashboard.view'
  | 'trips.view'
  | 'trips.create'
  | 'trips.edit'
  | 'trips.publish'
  | 'trips.archive'
  | 'trips.delete'
  | 'bookings.view'
  | 'bookings.create'
  | 'bookings.edit'
  | 'bookings.approve'
  | 'bookings.reject'
  | 'bookings.verify'
  | 'payments.view'
  | 'payments.edit'
  | 'inquiries.view'
  | 'inquiries.create'
  | 'inquiries.edit'
  | 'quotations.view'
  | 'quotations.create'
  | 'quotations.edit'
  | 'customers.view'
  | 'customers.export'
  | 'customers.timeline.view'
  | 'seo.view'
  | 'seo.edit'
  | 'guides.view'
  | 'guides.manage'
  | 'operations.view'
  | 'operations.edit'
  | 'ops.view'
  | 'ops.manage'
  | 'ops.allocate'
  | 'ops.checklist'
  | 'vendors.view'
  | 'vendors.create'
  | 'vendors.edit'
  | 'vendors.import'
  | 'reports.view'
  | 'reports.export'
  | 'users.view'
  | 'users.manage'
  | 'roles.manage'
  | 'staff_profiles.view'
  | 'staff_profiles.manage'
  | 'roles_permissions.manage'
  | 'payroll.view'
  | 'payroll.manage'
  | 'attendance.view'
  | 'attendance.manage'
  | 'marketing.social'
  | 'accounting.view'
  | 'accounting.submit'
  | 'accounting.approve'
  | 'tickets.view'
  | 'tickets.create'
  | 'tickets.edit'
  | 'tickets.submit'
  | 'tickets.approve'
  | 'tickets.templates.manage'
  | 'emails.view'
  | 'emails.send'
  | 'emails.manage_templates'
  | 'company_documents.view'
  | 'audit.view'
  | 'hr.view'
  | 'settings.view'
  | 'settings.edit';

export function isFounder(user: { role?: string; email?: string | null; name?: string | null } | null): boolean {
  if (!user) return false;
  const email = (user.email || '').toLowerCase().trim();
  return user.role === 'superadmin' && (email === 'hemal.patel@youthcamping.online' || email.includes('hemal'));
}
